### ISSUE TITLE
[feat]内置html优化和标签功能

### ISSUE THREAD

**Issue by zhanbuyu** [ayangweb/EcoPaste#100]
### Describe the problem

剪切板的出现以下问题：
1.复制html剪切板出现多个复制，
2.点击html复制直接内置打开，

可以添加标签功能，用户可以自由定义内容的的作用。

### Describe the solution you'd like

1.复制html内容的，过滤多余的复制内容。
2.点击heml内容的时候，调用默认浏览器打开。

**Comment by ayangweb** [comment]
这个 issue 由于长时间未回复，我先关闭了，标签功能暂时不会考虑，后期可以单独拉个 issue 出来支持他！
