### ISSUE TITLE
[feat] 点击条目自动上屏

### ISSUE THREAD

**Issue by klxq520** [ayangweb/EcoPaste#101]
### Describe the problem

我想像ClipboardFusion一样，点击文本条目自动上屏，如果条目是文件的话可以直接粘贴到当前目录，但ClipboardFusion是收费的，希望以后能加入这些功能。

### Describe the solution you'd like

我想像ClipboardFusion一样，点击文本条目自动上屏，如果条目是文件的话可以直接粘贴到当前目录，但ClipboardFusion是收费的，希望以后能加入这些功能。

**Comment by ayangweb** [comment]
感谢反馈，我没用过这个软件，你所谓的自动上屏是想说回填剪切板内容吗？

**Comment by Half1900** [comment]
> 感谢反馈，我没用过这个软件，你所谓的自动上屏是指把剪切板内容直接粘贴到其它地方，而不需要复制操作是吗？

是的，比如光标在微信聊天窗口，我点击echo上的条目时，会自动粘贴到微信对话框上去

**Comment by ayangweb** [comment]
Duplicate of #29 ，这个功能将会在以后的版本中支持，当前也欢迎 pr！

**Comment by ayangweb** [comment]
#169 功能已实现，期待下个版本！

**Comment by ayangweb** [comment]
https://github.com/ayangweb/EcoPaste/pull/170 文件和非文件的自动回填功能均已支持，期待下个版本！

**Comment by klxq520** [comment]
> 感谢反馈，我没用过这个软件，你所谓的自动上屏是指把剪切板内容直接粘贴到其它地方，而不需要复制操作是吗？

是的，就是自动粘贴到光标处，不用再按一次ctrl+v，如果条目是文件的话可以直接粘贴到当前目录或当天聊天窗口

**Comment by ayangweb** [comment]
> > 感谢反馈，我没用过这个软件，你所谓的自动上屏是指把剪切板内容直接粘贴到其它地方，而不需要复制操作是吗？
> 
> 是的，就是自动粘贴到光标处，不用再按一次ctrl+v，如果条目是文件的话可以直接粘贴到当前目录或当天聊天窗口

感谢反馈，#170 已支持，期待下个版本！
