### ISSUE TITLE
[feat] 建议打开面板后光标自动锁定搜索框, 可以直接输入要搜索的内容

### ISSUE THREAD

**Issue by two867** [ayangweb/EcoPaste#106]
### Describe the problem

打开剪贴板输入内容直接模糊匹配内容, 不需要鼠标点击一下搜索框再输入

### Describe the solution you'd like

打开剪贴板输入内容直接模糊匹配内容, 不需要鼠标点击一下搜索框再输入

**Comment by ayangweb** [comment]
感谢反馈，这个问题会和 #98 在后续版本一起优化！

**Comment by ayangweb** [comment]
#131 期待下个版本更新！
