### ISSUE TITLE
[bug] 任务管理器中为什么启动时会带这么多chrome 

### ISSUE THREAD

**Issue by amaoo** [ayangweb/EcoPaste#108]
### Describe the bug

![image](https://github.com/user-attachments/assets/160d6f5a-3670-4e01-9972-e4f86e392c44)
![image](https://github.com/user-attachments/assets/cb5b6961-580d-456c-af60-fcfeca46f578)

### Reproduction

PC 启动影响高

### Expected behavior

剪贴板不应该与 chrome 有什么关系

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.3",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by amaoo** [comment]
@AuroraTea 麻烦作者删除下 # 107  ，用错账号了

**Comment by amaoo** [comment]
还有几个 Microsoft Edge WebView2

**Comment by ayangweb** [comment]
> 还有几个 Microsoft Edge WebView2

感谢反馈，Microsoft Edge WebView2 这个是正常的，app 就是调用 WebView2 运行的，关于 chrome 有可能是你电脑造成的！
