### ISSUE TITLE
点击后直接插入[feat] 

### ISSUE THREAD

**Issue by amaoo** [ayangweb/EcoPaste#109]
### Describe the problem

![image](https://github.com/user-attachments/assets/61224f6a-ca59-47ae-b8d3-e3dca4d98a83)

### Describe the solution you'd like

类似于 windows 自带 的  Win + V 快捷键，点击后直接输入

**Comment by ayangweb** [comment]
Duplicate of #29 问题重复，期待后续版本支持！也欢迎 pr

**Comment by ayangweb** [comment]
#169 功能已实现，期待下个版本！
