### ISSUE TITLE
[bug] 通用设置页，无法清空快捷键设定

### ISSUE THREAD

**Issue by luxiao0000** [ayangweb/EcoPaste#118]
### Describe the bug

通用设置页，无法清空快捷键设定

### Reproduction

～

### Expected behavior

能清空快捷键设定

### Application and system information

```text
app version 0.0.3
---------------------
MacBook Pro
2.4 GHz 四核Intel Core i5
macos 14.5 (23F79)
```

**Comment by ayangweb** [comment]
收到反馈，将在后续版本加入清除快捷键功能！

**Comment by ayangweb** [comment]
#124 已支持，期待下个版本！
