### ISSUE TITLE
条目比较多的时候，希望可以快速回到底部/顶部[feat] 

### ISSUE THREAD

**Issue by Half1900** [ayangweb/EcoPaste#127]
### Describe the problem

数据较多时，又想回到条目最顶部，在没有一键回到顶部的按钮时，会很费时费力

### Describe the solution you'd like
![mmexport1721054481375.png](https://github.com/user-attachments/assets/63fbabaf-df75-41b9-bc65-12fbf9c92bef)

在底部或顶部某个位置增加一个返回顶部/底部的按钮，可以一键直达

**Comment by ayangweb** [comment]
收到反馈，后续版本会加入回到顶部的按钮！

**Comment by Half1900** [comment]
> 收到反馈，后续版本会加入回到顶部的按钮！

新增#Idea：如果没有单个条目置顶功能的，希望可以加一个，有些时候需要重复使用同一条数据，怕复制其它数据多了，会被顶掉

**Comment by ayangweb** [comment]
> > 收到反馈，后续版本会加入回到顶部的按钮！
> 
> 新增#Idea：如果没有单个条目置顶功能的，希望可以加一个，有些时候需要重复使用同一条数据，怕复制其它数据多了，会被顶掉

这个功能有点意思哈，这个可以单独拉个 issue 出来！🥰

**Comment by ayangweb** [comment]
#138 已支持，期待下个版本！
