### ISSUE TITLE
[bug] 搜索到的内容显示异常

### ISSUE THREAD

**Issue by TimelessDreamer** [ayangweb/EcoPaste#130]
### Describe the bug

搜索内容时，如果滚动条已经往下滚动了一部分距离，输入搜索内容后，滚动条没有滚动到最上面，而是一直停留在原来的位置！

<img width="390" alt="image" src="https://github.com/user-attachments/assets/558700e5-7650-47f7-80eb-88588a0b52f4">

### Expected behavior

希望滚动到最上面！

<img width="390" alt="image" src="https://github.com/user-attachments/assets/49a7e026-5369-48cb-a344-fccad597fa04">

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.3",
  "tauriVersion": "1.7.1",
  "platform": "Darwin",
  "platformArch": "aarch64",
  "platformVersion": "14.4.0"
}
```

**Comment by ayangweb** [comment]
收到反馈，这个问题将在下个版本修复！

**Comment by ayangweb** [comment]
#133 已修复，期待下个版本！
