### ISSUE TITLE
[feat] 建议新增一个“双击自动填充”的功能

### ISSUE THREAD

**Issue by xiaowulang-turbo** [ayangweb/EcoPaste#147]
### Describe the problem

具体应用场景为：在某个输入场景下，比如word或者命令行中，按下快捷键快速打开软件界面，之后双击想要填空的内容，即可将内容快速添加到windows光标之后。这样便免去了复制粘贴的过程。（windows自带的剪贴板，单击即可快速填充内容，个人认为十分方便）

### Describe the solution you'd like

可能需要与windows中的相关api进行交互。请开发者评估issue需求和难度，并考虑是否有开发计划。

**Comment by ayangweb** [comment]
Duplicate of #29 问题重复，这个功能正在研究，敬请期待！

**Comment by ayangweb** [comment]
#169 功能已实现，期待下个版本！
