### ISSUE TITLE
[feat] 功能建议

### ISSUE THREAD

**Issue by Norman-Jean** [ayangweb/EcoPaste#148]
### Describe the problem

1. 现在软件为安装形式，数据库也保存在用户目录里
2. 呼出菜单后的操作；

### Describe the solution you'd like

1. 希望软件做成绿色软件，数据库保存在软件目录里；
2. 呼出菜单后希望鼠标点击选项上屏，点击哪个复制选项哪个就能输出到光标处；
3. 感谢作者设计的软件。

**Comment by ayangweb** [comment]
收到反馈

1、这个功能不会考虑，因为我们都是通过 ci 完成打包的，只能打包出 msi 的安装包，内置更新功能，方便许多！
2、Duplicate of #29 ，这个问题正在研究，敬请期待！

**Comment by ayangweb** [comment]
#169 回填功能已实现，期待下个版本！
