### ISSUE TITLE
[bug] 复制粘贴Bug

### ISSUE THREAD

**Issue by Half1900** [ayangweb/EcoPaste#158]
### Describe the bug

https://github.com/user-attachments/assets/58b7b083-5fe7-4cb0-9c7a-dcf289e5f30d

数据条目上的复制icon，点击之后，有些数据有反应会更新位置，有些无反应；且有反应的部分数据，无法粘贴，没有反应的数据更无法粘贴

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.4",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
收到反馈，我在 MacOS 和 Windows 虚拟机测试均正常，你重启 app 试试！

**Comment by Half1900** [comment]
> 收到反馈，我在 MacOS 和 Windows 虚拟机测试均正常，你重启 app 试试！

重启了软件和电脑，还是存在这个bug

**Comment by ayangweb** [comment]
#159 修复了复制 html 没反应的问题

Duplicate of #151 后期会优化目标文件不存在时的处理
