### ISSUE TITLE
[bug] 复制偏好设置里的导航链接，点击直接替换了 app 页面

### ISSUE THREAD

**Issue by TimelessDreamer** [ayangweb/EcoPaste#164]
### Describe the bug

复制偏好设置里的导航链接，点击直接替换了 app 页面

https://github.com/user-attachments/assets/edc79e34-8826-4313-a63f-d3a344939763

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.4",
  "tauriVersion": "1.7.1",
  "platform": "Darwin",
  "platformArch": "aarch64",
  "platformVersion": "14.4.0"
}
```

**Comment by ayangweb** [comment]
收到反馈，下个版本会修复此问题！
