### ISSUE TITLE
[bug] 删除历史功能稳定无响应

### ISSUE THREAD

**Issue by Cattle0Horse** [ayangweb/EcoPaste#166]
### Describe the bug

右键一条剪贴内容, 点击删除后立即卡死未响应

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.4",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by ayangweb** [comment]
收到反馈，我这边排查一下！

**Comment by ayangweb** [comment]
https://github.com/user-attachments/assets/146e470a-bf61-4344-aa59-f5ab78a03597

我这边测试是正常的，方便的话录个屏看看吧！

**Comment by Cattle0Horse** [comment]
Uploading bandicam 2024-07-19 20-47-35-466.mp4…

现在甚至不用点击就未响应了

**Comment by Cattle0Horse** [comment]
https://github.com/user-attachments/assets/64ac5444-42f4-44b8-a672-09a825ef9540


现在甚至还没点击就未响应了

**Comment by ayangweb** [comment]
> bandicam.2024-07-19.20-47-35-466.mp4 
> 现在甚至还没点击就未响应了

你是 win 10 吗? 剪切板 ui 咋也变成这样了😢

**Comment by ayangweb** [comment]
> > > bandicam.2024-07-19.20-47-35-466.mp4
> > > 现在甚至还没点击就未响应了
> > 
> > 
> > 你是 win 10 吗? 剪切板 ui 咋也变成这样了😢
> 
> 是 win10, 很多软件都是这样

那就很尴尬，我们目前没有一台 win10 以供调试使用的！

**Comment by Half1900** [comment]
@Cattle0Horse，你好，经过测试，win10上未能复现删除卡死的问题，检查看看是不是与其它app冲突导致的？

https://github.com/user-attachments/assets/a46b2096-50e0-456a-ab72-bf2d176c1bfc

**Comment by Cattle0Horse** [comment]
> @Cattle0Horse，你好，经过测试，win10上未能复现删除卡死的问题，检查看看是不是与其它app冲突导致的？
> 
>  20240721_213234.mp4

经过测试, 我发现当我运行[网易有道翻译桌面版](https://fanyi.youdao.com/download-Windows?keyfrom=fanyiweb_navigation)并右键触发剪贴板栏时, 他会出现这个情况, 我的网易有道翻译版本是`10.2.9`

**Comment by ayangweb** [comment]
https://github.com/user-attachments/assets/353875a7-ae18-4b3e-a85d-f77087d56c9d

`10.3.0` 测试正常，更新一下试试呢？
