### ISSUE TITLE
[bug] UI-剪切板-点击删除 icon，出现气泡弹框，导致出现滚动条

### ISSUE THREAD

**Issue by kohaiy** [ayangweb/EcoPaste#182]
### Describe the bug

剪切板-点击删除 icon，出现气泡弹框，导致出现滚动条

![image](https://github.com/user-attachments/assets/40f83cea-bdb4-4bb2-bf5c-78e61ce4924b)

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.4",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by ayangweb** [comment]
限制一下 Popconfirm 的最大宽度应就可以了！

`rootClassName="max-w-300"`
