### ISSUE TITLE
[feat] 是否可以提供最小化到托盘图标的启动支持？

### ISSUE THREAD

**Issue by moonlune** [ayangweb/EcoPaste#189]
### Describe the problem

发现 Windows下 软件启动，如果设置开机启动，那么开机启动就会打开窗口。

### Describe the solution you'd like

不知是否可以提供最小化到托盘图标的启动支持？或者说有此功能我没有看到？当然实在没有，我可能需要自己写个启动器了。

**Comment by ayangweb** [comment]
收到反馈，我接下来会研究下如何判断是自动启动还是手动启动的 app，然后再支持自动启动时默认隐藏 app 的功能！

**Comment by ayangweb** [comment]
#211 已支持开机启动不显示窗口，期待下个版本！
