### ISSUE TITLE
[bug] 图片复制粘贴后颜色异常

### ISSUE THREAD

**Issue by kohaiy** [ayangweb/EcoPaste#221]
### Describe the bug

经过 [EcoPaste](https://github.com/ayangweb/EcoPaste) 复制后的图片，粘贴到微信、钉钉等地方，图片颜色会变得跟原图不一样。

- 原图

![image](https://github.com/user-attachments/assets/1a9c5e1b-edae-4907-a665-3a066548bdfc)

- 复制粘贴后的图
![1721887115120](https://github.com/user-attachments/assets/0e2b88ea-c75c-4b4d-a777-2eecb7f22647)

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.4",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by ayangweb** [comment]
问题跟踪：https://github.com/ChurchTao/clipboard-rs/issues/35
