### ISSUE TITLE
[feat] 增加重新唤起剪贴板时清空搜索框的选项

### ISSUE THREAD

**Issue by ElluIFX** [ayangweb/EcoPaste#240]
### Describe the problem

大部分情况下搜索过往记录只用一次，重新打开时还需要手动清空搜索框

### Describe the solution you'd like

增加能在重新唤起剪贴板时清空搜索框的选项

**Comment by ayangweb** [comment]
收到反馈，后续版本会支持！

**Comment by ayangweb** [comment]
#278 已支持，期待下个版本！

**Comment by ElluIFX** [comment]
> #278 已支持，期待下个版本！

Nice
