### ISSUE TITLE
windows 固定窗口自动粘贴时会先隐藏窗口再显示？想反馈此问题和懂 windows 原生 api 的大佬看过来😋！

### ISSUE THREAD

**Issue by ayangweb** [ayangweb/EcoPaste#249]
由于我的技术受限，询问了 g 大师等各种 ai 工具以及查看各种 rust 类似项目的源码（均未实现固定窗口时的自动粘贴，没得参考），依然无法解决这个问题。只能暂时以标题所示的方法实现！

在此，我真诚地希望有大佬能够提供一些灵感或提交 PR 来解决这个问题，非常感谢！🌹

针对这个问题，我想到两种可能的解决方案：

1. 像 [macos](https://github.com/ayangweb/EcoPaste/blob/master/src-tauri/src/core/app/macos.rs) 一样实时监听窗口聚焦状态的变化，把窗口进程 id 存起来！
2. 获取打开 EcoPaste 之前获取过焦点的窗口让它再次聚焦！

代码位置：
https://github.com/ayangweb/EcoPaste/blob/de4ab2842e785a2b6ba6cbeabd0438369f6990af/src-tauri/src/plugins/paste.rs#L32

**Comment by RSS1102** [comment]
均未实现固定窗口时的自动粘贴，如何理解呢？
你可以关注一下[windows-rs](https://github.com/microsoft/windows-rs)
 是否提供了你想要的api。

**Comment by ayangweb** [comment]
> 均未实现固定窗口时的自动粘贴，如何理解呢？ 你可以关注一下[windows-rs](https://github.com/microsoft/windows-rs) 是否提供了你想要的api。

谢谢，用过 windows-rs 或者 winapi 等各种库，可能是我给 g 大师的描述不正确，未能达到预期的效果！

**Comment by ayangweb** [comment]
> 均未实现固定窗口时的自动粘贴，如何理解呢？ 
其它 app 未实现固定窗口的自动粘贴，没得参考😂

> 你可以关注一下[windows-rs](https://github.com/microsoft/windows-rs) 是否提供了你想要的api。

谢谢，用过 windows-rs 或者 winapi 等各种库，可能是我给 g 大师的描述不正确，未能达到预期的效果！

**Comment by ChurchTao** [comment]
```rust
// 让上一个窗口聚焦（windows）
#[cfg(target_os = "windows")]
fn focus_previous_window() {
    use winapi::um::winuser::{GetForegroundWindow, SetForegroundWindow};

    unsafe {
        let hwnd = GetForegroundWindow();

        if hwnd.is_null() {
            println!("Could not get active window");
            return;
        }

        if SetForegroundWindow(hwnd) == 0 {
            println!("Could not focus on window");
        }
    }
}
```
你这代码有问题吧，这语言不是  获取当前活跃的窗口句柄，然后再把 这个窗口设置为前置窗口吗？

我之前的思路是 你的应用 beforeOnShow 的时候，去记录当前活动的窗口句柄（此乃 前活跃窗口），然后你粘贴的时候，去对这个窗口句柄调用 `SetForegroundWindow` , 然后他就前置了（无论你是否PIN住了你的窗口，SetForegroundWindow优先级很高），你的 `sendInput` 就会对他有效。

**Comment by ayangweb** [comment]
> ```rust
> // 让上一个窗口聚焦（windows）
> #[cfg(target_os = "windows")]
> fn focus_previous_window() {
>     use winapi::um::winuser::{GetForegroundWindow, SetForegroundWindow};
> 
>     unsafe {
>         let hwnd = GetForegroundWindow();
> 
>         if hwnd.is_null() {
>             println!("Could not get active window");
>             return;
>         }
> 
>         if SetForegroundWindow(hwnd) == 0 {
>             println!("Could not focus on window");
>         }
>     }
> }
> ```
> 
> 你这代码有问题吧，这语言不是 获取当前活跃的窗口句柄，然后再把 这个窗口设置为前置窗口吗？
> 
> 我之前的思路是 你的应用 beforeOnShow 的时候，去记录当前活动的窗口句柄（此乃 前活跃窗口），然后你粘贴的时候，去对这个窗口句柄调用 `SetForegroundWindow` , 然后他就前置了（无论你是否PIN住了你的窗口，SetForegroundWindow优先级很高），你的 `sendInput` 就会对他有效。

大佬，看了您之前评论的，让 g 大师写，可能是我描述的有问题，没能解决，呜呜呜，我下来会在试试询问描述，再多试试！

**Comment by ChurchTao** [comment]
> ```rust
> // 让上一个窗口聚焦（windows）
> #[cfg(target_os = "windows")]
> fn focus_previous_window() {
>     use winapi::um::winuser::{GetForegroundWindow, SetForegroundWindow};
> 
>     unsafe {
>         let hwnd = GetForegroundWindow();
> 
>         if hwnd.is_null() {
>             println!("Could not get active window");
>             return;
>         }
> 
>         if SetForegroundWindow(hwnd) == 0 {
>             println!("Could not focus on window");
>         }
>     }
> }
> ```
> 
> 你这代码有问题吧，这语言不是 获取当前活跃的窗口句柄，然后再把 这个窗口设置为前置窗口吗？
> 
> 我之前的思路是 你的应用 beforeOnShow 的时候，去记录当前活动的窗口句柄（此乃 前活跃窗口），然后你粘贴的时候，去对这个窗口句柄调用 `SetForegroundWindow` , 然后他就前置了（无论你是否PIN住了你的窗口，SetForegroundWindow优先级很高），你的 `sendInput` 就会对他有效。

哦，我那个仓库里，windows的代码是别人pr贡献的。。我没仔细看过，可能是有问题，你可以看下这个https://learn.microsoft.com/zh-cn/windows/win32/api/winuser/nf-winuser-setforegroundwindow

**Comment by ayangweb** [comment]
> 可能是有问题，你可以看下这个

是滴，我看 pr 是别人贡献的，再没有固定窗口的功能的时候，用起来确实非常方便😋

**Comment by ayangweb** [comment]
> > ```rust
> > // 让上一个窗口聚焦（windows）
> > #[cfg(target_os = "windows")]
> > fn focus_previous_window() {
> >     use winapi::um::winuser::{GetForegroundWindow, SetForegroundWindow};
> > 
> >     unsafe {
> >         let hwnd = GetForegroundWindow();
> > 
> >         if hwnd.is_null() {
> >             println!("Could not get active window");
> >             return;
> >         }
> > 
> >         if SetForegroundWindow(hwnd) == 0 {
> >             println!("Could not focus on window");
> >         }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你这代码有问题吧，这语言不是 获取当前活跃的窗口句柄，然后再把 这个窗口设置为前置窗口吗？
> > 我之前的思路是 你的应用 beforeOnShow 的时候，去记录当前活动的窗口句柄（此乃 前活跃窗口），然后你粘贴的时候，去对这个窗口句柄调用 `SetForegroundWindow` , 然后他就前置了（无论你是否PIN住了你的窗口，SetForegroundWindow优先级很高），你的 `sendInput` 就会对他有效。
> 
> 哦，我那个仓库里，windows的代码是别人pr贡献的。。我没仔细看过，可能是有问题，

是滴，我看 pr 是别人贡献的，再没有固定窗口的功能的时候，用起来确实非常方便😋

> 你可以看下这个 https://learn.microsoft.com/zh-cn/windows/win32/api/winuser/nf-winuser-setforegroundwindow

好嘞，我在让 g 大师帮帮我！

**Comment by ayangweb** [comment]
fixed:

- #259 
- #291 

感谢 @ChurchTao 大佬提供的思路🌹
