### ISSUE TITLE
[bug] 复制文本之后，尝试再打开页面进程自动退出

### ISSUE THREAD

**Issue by RSS1102** [ayangweb/EcoPaste#251]
### Describe the bug

当我复制完当前页面的链接，我想通过右下角图标想打开软件的时候，软件会自动退出。

但是复制其他文本或者某些其他链接不会自动退出。
https://github.com/user-attachments/assets/f4dedce0-65b7-4c5e-a70d-f0a7e1fc4aa2

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
收到反馈，我们下来排查一下！

**Comment by ayangweb** [comment]
我这边测试了一下，是正常的🥹

https://github.com/user-attachments/assets/7251ff99-6961-478f-825d-558ff94362ad

**Comment by WyInnovate** [comment]
@RSS1102 
事件查看器 应用程序里应该能看到崩溃日志
我也有闪退问题、群友也有，不知道你这个是否是一样的，能看一下事件查看器里有日志吗？

**Comment by ayangweb** [comment]
Duplicate of #303 

问题原因都是一样哒，这个 issue 我先关了，等更新！
