### ISSUE TITLE
[bug] 文本显示成代码，图片不能预览The text is displayed as code and the image cannot be previewed

### ISSUE THREAD

**Issue by hanvcc** [ayangweb/EcoPaste#257]
### Describe the bug

![2024-07-30 at 09 26 08](https://github.com/user-attachments/assets/143cbb93-7041-4e40-994b-300dbf727404)

### Application and system information

```text
imac  
3.6 GHz 十核Intel Core i9
AMD Radeon Pro 5700 8 GB
32 GB 2667 MHz DDR4
macos 14.4.1
EcoPaste 0.0.5
```

**Comment by ayangweb** [comment]
感谢反馈：

1. Duplicate of #151 问题重复，下个版本会进行文件展示优化
2. Duplicate of #36 问题重复，等库作者完全支持富文本内容的获取，会支持富文本正常渲染内容

**Comment by ayangweb** [comment]
#405 #414 已优化🌹
