### ISSUE TITLE
[bug] windows 系统打不开，一直闪退（无限重启）解决方案：暂时用管理员启动或者下载 0.0.4 版本使用！

### ISSUE THREAD

**Issue by sjxthxh** [ayangweb/EcoPaste#269]
### Describe the bug

https://github.com/user-attachments/assets/a32e92d5-0a6a-4b45-977e-144df8e128d9

### Application and system information

```text
软件打不开
```

**Comment by ayangweb** [comment]
感谢反馈！麻烦系统信息发一下，谢谢！

<img width="830" alt="image" src="https://github.com/user-attachments/assets/e473a0c2-3001-4cd2-8e9a-99ad4b74cdea">

**Comment by Jonnyan404** [comment]
我是重启机器后恢复，
可能跟不是安装在C盘有关系.

**Comment by kohaiy** [comment]
托盘里有图标吗？

**Comment by kohaiy** [comment]
现在是没问题了吗？

**Comment by sjxthxh** [comment]
> 托盘里有图标吗？

一会有一会没有

**Comment by sjxthxh** [comment]
> 感谢反馈！麻烦系统信息发一下，谢谢！
> 
> <img alt="图像" width="830" src="https://private-user-images.githubusercontent.com/75017711/354047852-e473a0c2-3001-4cd2-8e9a-99ad4b74cdea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODA1NjksIm5iZiI6MTcyMjQ4MDI2OSwicGF0aCI6Ii83NTAxNzcxMS8zNTQwNDc4NTItZTQ3M2EwYzItMzAwMS00Y2QyLThlOWEtOTlhZDRiNzRjZGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAyNDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YjJmMGNhYmFiNDExYmJjYzZlYTI2MTdmZDJlOGZhMWE5ZTJkMWU5MTQ4OGU1ZTEwZmE3MzdhZGY2MjE0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CmVQhku4nWaO8rW7SihCo6StuWpNctkW7Q_1qWpen0I">

进入不了这个界面，启动就不断重启了，操作不了

**Comment by sjxthxh** [comment]
> 我是重启机器后恢复， 可能跟不是安装在C盘有关系. 机器配置低的，按重启按钮的手速要快，不然直接闪没了，或者直接硬重启.

我换成c盘还是不行

**Comment by ayangweb** [comment]
> > 感谢反馈！麻烦系统信息发一下，谢谢！
> > <img alt="图像" width="830" src="https://private-user-images.githubusercontent.com/75017711/354047852-e473a0c2-3001-4cd2-8e9a-99ad4b74cdea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODA1NjksIm5iZiI6MTcyMjQ4MDI2OSwicGF0aCI6Ii83NTAxNzcxMS8zNTQwNDc4NTItZTQ3M2EwYzItMzAwMS00Y2QyLThlOWEtOTlhZDRiNzRjZGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAyNDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YjJmMGNhYmFiNDExYmJjYzZlYTI2MTdmZDJlOGZhMWE5ZTJkMWU5MTQ4OGU1ZTEwZmE3MzdhZGY2MjE0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CmVQhku4nWaO8rW7SihCo6StuWpNctkW7Q_1qWpen0I">
> 
> 进入不了这个界面，启动就不断重启了，操作不了

糊涂了😂发一下电脑关于本机截图也行

**Comment by sjxthxh** [comment]
> > > 感谢反馈！麻烦系统信息发一下，谢谢！
> > > <img alt="图像" width="830" src="https://private-user-images.githubusercontent.com/75017711/354047852-e473a0c2-3001-4cd2-8e9a-99ad4b74cdea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODA1NjksIm5iZiI6MTcyMjQ4MDI2OSwicGF0aCI6Ii83NTAxNzcxMS8zNTQwNDc4NTItZTQ3M2EwYzItMzAwMS00Y2QyLThlOWEtOTlhZDRiNzRjZGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAyNDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YjJmMGNhYmFiNDExYmJjYzZlYTI2MTdmZDJlOGZhMWE5ZTJkMWU5MTQ4OGU1ZTEwZmE3MzdhZGY2MjE0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CmVQhku4nWaO8rW7SihCo6StuWpNctkW7Q_1qWpen0I">
> > 
> > 
> > 进入不了这个界面，启动就不断重启了，操作不了
> 
> 糊涂了😂发一下电脑关于本机截图也行

![image](https://github.com/user-attachments/assets/d438d187-5593-4dae-932b-e82733e08cfe)

**Comment by sjxthxh** [comment]
![image](https://github.com/user-attachments/assets/6341bc6a-e132-44be-a168-e435dcfcf1c4)
没有保存信息

**Comment by JimmyBeck** [comment]
我也是同样的情况
![image](https://github.com/user-attachments/assets/18e8c6f4-9e27-4f40-875b-5b2cb37c3659)

**Comment by JimmyBeck** [comment]
> 可以在命令行运行软件看看有没有报错信息吗？ 打开命令行，进入 EcoPaste 的安装目录，然后执行 `.\EcoPaste.exe` 来启动。
> 
> > 安装目录可以在 EcoPaste 上右键打开文件位置，如果还是快捷方式，就继续右键打开文件位置。

使用了这个方案，依旧不行。依旧是一直闪退，再重新开启，再闪退。详见视频：
https://github.com/user-attachments/assets/d2edb392-0b0c-4e9d-a155-2ca24d24c83a

**Comment by ayangweb** [comment]
大家好，

很抱歉给大家带来困扰。由于技术原因，当前版本没有日志功能，给大家带来的不便敬请谅解。我们将在后续版本中补上这一功能。

如果遇到闪退问题，并且您具备开发经验，我们非常欢迎您与我们一起探讨解决方案。我们在多台 Windows 设备上测试时并未复现该问题，希望通过 dev 模式能够更好地排查此问题。非常感谢您的理解与支持！🌹

再次感谢大家的耐心和帮助！

**Comment by ayangweb** [comment]
大家好，如果您在使用0.0.5版本时遇到闪退问题，建议您尝试下载0.0.5之前的版本，并向我们反馈是否还存在同样的问题。感谢您的理解与支持，我们将持续改进以提供更好的体验。🥰

**Comment by ayangweb** [comment]
大家好，我找到了一款能复现 0.0.5 闪退的机子，目前想使用的同学可以暂时先下载 0.0.4 版本使用，我们会尽快修复此问题，并且发布新版本！

**Comment by asundust** [comment]
Windows使用管理员启动可以启动成功

**Comment by ayangweb** [comment]
> Windows使用管理员启动可以启动成功

感谢反馈，我这边测试确实如此，我们会尽快排查产生的原因🌹

**Comment by ayangweb** [comment]
> chrome_hBxNB9muzi.mp4 
> 结束都结束不了，，我是不是中毒了

您好，您可以再次双击 MSI 文件，会出现删除选项，将应用程序卸载。目前的解决方案是以管理员权限打开程序或下载 0.0.4 版本。我们会尽快排查此问题并修复，感谢您的理解和支持🌹

**Comment by imshixin** [comment]
我在它不断重启的过程中打开资源管理器，进入c盘，它就好了😂

**Comment by ayangweb** [comment]
> 我在它不断重启的过程中打开资源管理器，进入c盘，它就好了😂

这个问题太奇怪了，到现在还是没有一点解决思路，太难了😥

**Comment by ayangweb** [comment]
各位好，#327 无限重启的 bug 已修复🎉

**Comment by ayangweb** [comment]
https://github.com/ayangweb/EcoPaste/releases/tag/v0.0.6 最新版已修复此问题，谢谢大家的理解和支持🌹
