### ISSUE TITLE
老师,能发布免安装的版本吗?[feat] 

### ISSUE THREAD

**Issue by SoyKoa** [ayangweb/EcoPaste#270]
### Describe the problem

如题

### Describe the solution you'd like

如题

**Comment by ayangweb** [comment]
收到反馈，目前还没有测试在免安装的情况下自动更新功能是否正常，我们下来会测试下，如果有效的话，后续应该会直接放在官方网站中，网站还在建设中 🌹

**Comment by Redstone-1** [comment]
你的头像令我垂涎欲滴~

**Comment by guzzhao** [comment]
> 收到反馈，目前还没有测试在免安装的情况下自动更新功能是否正常，我们下来会测试下，如果有效的话，后续应该会直接放在官方网站中，网站还在建设中 🌹

希望支持scoop

**Comment by ayangweb** [comment]
> > 收到反馈，目前还没有测试在免安装的情况下自动更新功能是否正常，我们下来会测试下，如果有效的话，后续应该会直接放在官方网站中，网站还在建设中 🌹
> 
> 希望支持scoop

好，我们下来研究下🌹

**Comment by ayangweb** [comment]
@SoyKoa https://github.com/ayangweb/EcoPaste/releases/download/v0.0.6/EcoPaste_0.0.6_Windows_x64_Portable.zip

最新版已加入！

**Comment by SoyKoa** [comment]
感谢
