### ISSUE TITLE
[feat] 默认窗口位置添加自定义（记住上次位置）

### ISSUE THREAD

**Issue by Iphisxu** [ayangweb/EcoPaste#273]
### Describe the problem

目前打开剪切板窗口时仅支持“默认位置”、“屏幕中心”、“跟随鼠标”三个选项，其中默认位置比较怪异，它位于屏幕的左上方，尽管我手动调整它到我喜欢的位置后，再次打开窗口使用可以留在该位置，**然而在关闭电脑重启后，它又会回到左上方位置，需要我再次手动调整**。

### Describe the solution you'd like

建议对默认位置增加更多的自定义，或者记忆用户上一次关机前把窗口挪动的位置，这样不用在重启电脑后手动移动位置。

**Comment by ayangweb** [comment]
收到反馈，下个版本默认位置会改为记住位置

**Comment by ayangweb** [comment]
#347 已支持，期待下个版本
