### ISSUE TITLE
[feat] 动态修改主题

### ISSUE THREAD

**Issue by RSS1102** [ayangweb/EcoPaste#274]
### Describe the problem

尝试动态修改主题，不需要重启app。

### Describe the solution you'd like

https://github.com/wyhaya/tauri-plugin-theme

**Comment by ayangweb** [comment]
<img width="904" alt="image" src="https://github.com/user-attachments/assets/0c97fa64-6a42-4380-87dd-b16efa39f08d">

感谢反馈，目前用的就是这个插件，但是 windows 由于版本问题，目前没有一个合适的解决方案，只能重启修改主题！🌹
