### ISSUE TITLE
[feat] 有linux的appimage版嘛

### ISSUE THREAD

**Issue by xs-alpha** [ayangweb/EcoPaste#275]
希望出linux的appimage版

**Comment by ayangweb** [comment]
Duplicate of #75 问题重复！

收到反馈，目前 linux 版本还有一些功能正在做，敬请期待！也欢迎参与进 linux 的开发🌹

**Comment by zpp0196** [comment]
目前只有 deb 和 rpm，AppImage 还有点问题

**Comment by zpp0196** [comment]
#302
