### ISSUE TITLE
[feat] 双屏幕时，设置的跟随鼠标，但是只能显示在主屏幕上，无法显示到第二个屏幕

### ISSUE THREAD

**Issue by ALagom** [ayangweb/EcoPaste#276]
### Describe the problem

![Clip_2024-08-02_09-16-26](https://github.com/user-attachments/assets/b0547ac4-66e9-45da-af26-0fe9556daf7f)
双屏幕时，设置的跟随鼠标，但是只能显示在主屏幕上，无法显示到第二个屏幕

### Describe the solution you'd like

无法显示到第二屏幕

**Comment by ayangweb** [comment]
Duplicate of #64 问题重复

收到反馈，后续版本修复🌹

**Comment by ayangweb** [comment]
你好，#413 已经优化，欢迎加入我们的[微信群](https://github.com/ayangweb/EcoPaste?tab=readme-ov-file#community)进行测试🌹
