### ISSUE TITLE
[feat] 建议粘贴改成Shift+Insert模式

### ISSUE THREAD

**Issue by iridescent233** [ayangweb/EcoPaste#279]
### Describe the problem

在MobaXterm等终端软件中，粘贴快捷键是Shift+Insert，而非Ctrl+V，所以目前的方式在这类软件中无法使用。

### Describe the solution you'd like

改成Shift+Insert粘贴内容。

**Comment by zpp0196** [comment]
不同的终端有不同的粘贴方式，除了 Shift+Insert 还有 Ctrl+Shift+V 等，后续看看有没有通用的解决方案

**Comment by cyzzxc** [comment]
mobaxterm - setting - mobaxterm key board shortcut - paste in terminal 改为 ctrl + v 则可以使用
不过提供 Shift+Insert 进行粘贴会是个更通用的方案，Ctrl+V 在 shell 和 vim 中被占用

**Comment by ayangweb** [comment]
收到反馈，我们下来会研究一个通用的解决方案🌹

**Comment by ayangweb** [comment]
@iridescent233 @cyzzxc 两位好，我目前改变了写法解决此问题，欢迎加入[微信群](https://github.com/ayangweb/EcoPaste?tab=readme-ov-file#community)来帮忙测试效果！

**Comment by ayangweb** [comment]
@iridescent233 @cyzzxc 两位好，在 windows 中 shift+insert 是属于通用方案吗？可以适用于各种 app 是不，望回复🌹

**Comment by cyzzxc** [comment]
在我的使用场景下 shift+insert 比 ctrl + v 更通用，没遇到过不生效的情况。  可以参考ditto的情况：
https://github.com/sabrogden/Ditto/issues/682

ayang ***@***.***> 于2024年8月9日周五 08:08写道：
