### ISSUE TITLE
[bug] 未必是bug,但是为何win下会开启多个webview2进程?

### ISSUE THREAD

**Issue by xkonglong** [ayangweb/EcoPaste#282]
### Describe the bug

![image](https://github.com/user-attachments/assets/d8ee777f-c918-4261-85b4-75245d76079b)

为何win下会开启多个webview2进程?

虽然软件本身的资源占用低,但是加了这些进程的资源就高了.

### Application and system information

```text
win10 LTSC
```

**Comment by ayangweb** [comment]
感谢您的反馈。Tauri 项目通过与 Webview2 集成来运行，这是正常情况🌹

**Comment by ayangweb** [comment]
这个问题我先关啦，有其它问题欢迎随时 diss！🌹
