### ISSUE TITLE
[feat] 自定义存储位置

### ISSUE THREAD

**Issue by llkj0001** [ayangweb/EcoPaste#283]
### Describe the problem

目前存储位置位于用户缓存目录，容易造成重装系统丢失记录

### Describe the solution you'd like

希望默认存储位置在安装目录，并且支持自定义存储位置

**Comment by ayangweb** [comment]
Duplicate of #163 问题重复！

收到反馈，将在后续版本支持🌹

**Comment by ayangweb** [comment]
https://github.com/EcoPasteHub/EcoPaste/releases/tag/v0.1.0-beta.2

下载使用前请先手动备份好重要数据，然后再尝试更换路径！
