### ISSUE TITLE
[bug] 搜索时，主界面被隐藏

### ISSUE THREAD

**Issue by llkj0001** [ayangweb/EcoPaste#284]
### Describe the bug

Windows系统下，按alt + c呼出主页面，按ctrl + f 进行搜索，呼出搜索窗，但是主页面会消失

![image](https://github.com/user-attachments/assets/f314a96b-aa24-420f-a94b-e19377df7ea5)

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
收到反馈，哈哈，看样子是调用了浏览器的一些特殊的快捷键，我们会在后续版本禁掉这些干扰的快捷键，app 是自带搜索框的，用自带的搜索框哈！

<img width="390" alt="image" src="https://github.com/user-attachments/assets/39e37a54-66b4-4187-be7e-d97ee2fbf2fe">

**Comment by ayangweb** [comment]
统一回复，后续版本 cmd/ctrl + f 会被作为自定义搜索框的快捷键🌹

**Comment by ayangweb** [comment]
#298 已支持 Ctrl/Meta + F 聚焦自定义搜索框，期待下个版本！
