### ISSUE TITLE
win11 闪退[feat] 

### ISSUE THREAD

**Issue by feitianw** [ayangweb/EcoPaste#290]
### Describe the problem

win11 闪退[feat] 

### Describe the solution you'd like

win11 闪退[feat]

**Comment by ayangweb** [comment]
Duplicate of #269 问题重复

收到反馈，目前的解决方案是以管理员权限打开程序或下载 0.0.4 版本。我们会尽快排查此问题并修复，感谢您的理解和支持🌹
