### ISSUE TITLE
[bug] 任务管理器显示名称错误

### ISSUE THREAD

**Issue by WilliamZY** [ayangweb/EcoPaste#292]
### Describe the bug

任务管理器显示名称错误
![image](https://github.com/user-attachments/assets/d147f298-957c-46a0-8fda-78a75e596aac)

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
收到反馈，我们排查一下看看是什么情况哈🌹

**Comment by ayangweb** [comment]
#348 已修复，期待下个版本！
