### ISSUE TITLE
[feat] 建议双击自动填充功能

### ISSUE THREAD

**Issue by i-iooi-i** [ayangweb/EcoPaste#294]
### Describe the problem

![image](https://github.com/user-attachments/assets/70349aa8-a09e-48d2-a10b-af5401130182)

### Describe the solution you'd like

win11 自带的剪切板是支持这类功能。

比如把光标放在搜索框，回到剪切板界面双击某一条信息，这条信息就会被自动填充到光标输入框的位置。
体验起来还是很丝滑的，一个双击操作，省去了“复制”“粘贴”两个步骤。

**Comment by ayangweb** [comment]
收到反馈，这个需求在 0.0.5 是支持的哈！

<img width="830" alt="image" src="https://github.com/user-attachments/assets/f53132ff-bd57-45eb-8cf5-eb023aed28ee">
