### ISSUE TITLE
[feat] 窗口获取到焦点时，点击 `Ctrl F` 开启搜索

### ISSUE THREAD

**Issue by pheotry** [ayangweb/EcoPaste#295]
### Describe the problem

如题

### Describe the solution you'd like

搜索快捷键一般是 `Ctrl F`，快捷键相比鼠标操作更方便一些

**Comment by ayangweb** [comment]
Duplicate of #284 问题重复

收到反馈，后续版本会加入快捷键的方式！

**Comment by ayangweb** [comment]
#298 已支持，期待下个版本！
