### ISSUE TITLE
[feat] 呼出跟随鼠标位置

### ISSUE THREAD

**Issue by pheotry** [ayangweb/EcoPaste#296]
### Describe the problem

无法跟随输入框

### Describe the solution you'd like

如果可以类似Win的那种应该会更好，win的剪贴板不是跟随鼠标，试了下好像是跟随输入焦点的，如果没有输入，那就是上次的输入焦点位置。
如果不能实现的话，跟随鼠标位置也好点，固定左上角不是很方便

**Comment by ayangweb** [comment]
跟随光标位置：
Duplicate of #264 问题重复

跟随鼠标位置：
这个最新版支持的哈！
<img width="830" alt="image" src="https://github.com/user-attachments/assets/a86d49c0-ec78-4d4b-bb16-8de7bb3cba84">
