### ISSUE TITLE
[bug] 多屏环境下，打开跟随鼠标后，快捷键呼出时只能出现在主屏幕

### ISSUE THREAD

**Issue by chaojimct** [ayangweb/EcoPaste#297]
### Describe the bug

多屏环境下，打开跟随鼠标后，快捷键呼出时只能出现在主屏幕

### Application and system information

```text
win11
双屏
```

**Comment by ayangweb** [comment]
Duplicate of #64 问题重复

收到反馈，期待后续版本修复🌹

**Comment by ayangweb** [comment]
你好，#413 已经优化，欢迎加入我们的[微信群](https://github.com/ayangweb/EcoPaste?tab=readme-ov-file#community)进行测试🌹
