### ISSUE TITLE
[feat] 单击托盘唤醒剪切板窗口

### ISSUE THREAD

**Issue by 775405984** [ayangweb/EcoPaste#300]
### Describe the problem

![image](https://github.com/user-attachments/assets/3a328b19-dfdc-4490-9189-92d80642f599)
我不喜欢用键盘

### Describe the solution you'd like

我不喜欢用键盘，可不可以添加单击托盘唤醒窗口？

**Comment by ayangweb** [comment]
收到反馈，你要的唤醒窗口是指唤醒剪切板窗口吗？单击托盘打开窗口目前给偏好设置窗口服务的

**Comment by 775405984** [comment]
> 收到反馈，你要的唤醒窗口是指唤醒剪切板窗口吗？单击托盘打开窗口目前给偏好设置窗口服务的，下个版本去掉了该配置项，点击托盘默认打开偏好设置窗口！

是的，点击就打开剪切板窗口

**Comment by ayangweb** [comment]
好的，后续看看给个配置项，单击托盘自己选择打开哪个窗口！
