### ISSUE TITLE
[feat] 作者你好, 请问能否提供绿色免安装版呢?

### ISSUE THREAD

**Issue by th3Wisp** [ayangweb/EcoPaste#301]
### Describe the problem

如题 .... 感谢

### Describe the solution you'd like

如题 .... 感谢

**Comment by ayangweb** [comment]
Duplicate of #270 问题重复

问题重复，后续看情况会提供绿色包，目前先用 msi 安装包代替🌹

**Comment by ayangweb** [comment]
https://github.com/ayangweb/EcoPaste/releases/download/v0.0.6/EcoPaste_0.0.6_Windows_x64_Portable.zip

最新版已加入！
