### ISSUE TITLE
[bug] win11系统，软件在后台崩溃

### ISSUE THREAD

**Issue by Tgkkez** [ayangweb/EcoPaste#303]
### Describe the bug

![2024-08-03_19-33-22](https://github.com/user-attachments/assets/528635fb-53a9-45cf-9df1-8224e4e34ad7)
软件在后台运行着会突然自动关闭

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by Tgkkez** [comment]
卸载重装后，暂时没复现问题

**Comment by ayangweb** [comment]
> 卸载重装后，暂时没复现问题

谢谢反馈，目前没问题了就行！等有问题了再反馈🌹

**Comment by ayangweb** [comment]
这个问题我先关了，有问题随时反馈🌹

**Comment by WyInnovate** [comment]
@ayangweb 
我也有这个问题，然后我还没试过卸载重装
`
错误应用程序名称: EcoPaste.exe，版本: 0.0.5.0，时间戳: 0x66a6661a
错误模块名称: ntdll.dll，版本: 10.0.22621.3733，时间戳: 0x67ca8829
异常代码: 0xc0000374
错误偏移量: 0x000000000010c8f9
错误进程 ID: 0x0x5C78
错误应用程序启动时间: 0x0x1DAE7AC42AC0085
错误应用程序路径: C:\Program Files\EcoPaste\EcoPaste.exe
错误模块路径: C:\WINDOWS\SYSTEM32\ntdll.dll
报告 ID: 62d55863-1fef-4cef-bbd6-fbb5ad22cea4
错误程序包全名: 
错误程序包相对应用程序 ID: 
`
我的信息如下
`
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
`

**Comment by ayangweb** [comment]
@Tgkkez @WyInnovate 两位好，我不确定是不是因为 app 无限重启的 bug 导致的，我刚好这会修复了 app 重启的 bug，两位可以加一下 README 里的微信群，然后拿新的安装包再体验试一试！

**Comment by WyInnovate** [comment]
> @Tgkkez @WyInnovate 两位好，我不确定是不是因为 app 无限重启的 bug 导致的，我刚好这会修复了 app 重启的 bug，两位可以加一下 README 里的微信群，然后拿新的安装包再体验试一试！

好的，我加一下

**Comment by gohj99** [comment]
确实在win11上安装完成软件后窗口闪退又启动了好多次，ui在打开后每次复制消息就直接退出软件
然而在把软件gui关闭后问题解决了
并没有复现

**Comment by ayangweb** [comment]
> 确实在win11上安装完成软件后窗口闪退又启动了好多次，ui在打开后每次复制文本就直接退出软件 然而在把软件gui关闭后问题解决了 并没有复现

感谢大佬反馈，目前已经有大佬复现出来报错原因，我们也是在紧急的修复！

**Comment by ayangweb** [comment]
@WyInnovate @gohj99 二位好，如果你们未测试最新版的话，可以从下载最新的测试版本看看还不会不会崩溃 

https://github.com/ayangweb/EcoPaste/actions/runs/10500183819/artifacts/1840205163

**Comment by ayangweb** [comment]
@Tgkkez  @gohj99 二位好，如果你们未下载最新测试版的话，可以下载最新的测试版本看看还不会不会崩溃 

https://github.com/ayangweb/EcoPaste/actions/runs/10500183819/artifacts/1840205163

**Comment by ayangweb** [comment]
#380 + #416 已修复此问题，issue 我先关了，期待下个版本！
