### ISSUE TITLE
复制的表格 希望能选择 粘贴

### ISSUE THREAD

**Issue by visiLi** [ayangweb/EcoPaste#312]
### Describe the problem

粘贴方式，可以是粘贴，图片还是文本！

### Describe the solution you'd like

就像【ditto】

**Comment by ayangweb** [comment]
Duplicate of #212 问题重复

收到反馈，我们后续版本会有优化此问题🌹

**Comment by ayangweb** [comment]
重复的 issue 我先关了，等优化🌹
