### ISSUE TITLE
[bug] 复制代码就成鬼样子了

### ISSUE THREAD

**Issue by cethink** [ayangweb/EcoPaste#313]
### Describe the bug

![image](https://github.com/user-attachments/assets/bb363138-58a3-4d45-aefa-9c87500a5008)

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by cethink** [comment]
从Visual Studio 2022中复制的

**Comment by ayangweb** [comment]
Duplicate of #36  问题重复

收到反馈，后续版本优化，目前正在找合适能转换 rtf 的插件🌹

**Comment by ayangweb** [comment]
重复的 issue 我关了，后续等优化🌹

**Comment by cethink** [comment]
🌹

**Comment by ayangweb** [comment]
#414 已优化🌹
