### ISSUE TITLE
[feat] 本次数据存贮位置可自行调整

### ISSUE THREAD

**Issue by yanjingonline** [ayangweb/EcoPaste#314]
### Describe the problem

如题，希望增加本地数据保存位置可调整。

### Describe the solution you'd like

如题，希望增加本地数据保存位置可调整。

**Comment by ayangweb** [comment]
Duplicate of #163 

问题重复，我将关闭当前 issue，等后续支持🌹

**Comment by ayangweb** [comment]
https://github.com/EcoPasteHub/EcoPaste/releases/tag/v0.1.0-beta.2

下载使用前请先手动备份好重要数据，然后再尝试更换路径！
