### ISSUE TITLE
建议可以在菜单栏隐藏图标[feat] 

### ISSUE THREAD

**Issue by chww159** [ayangweb/EcoPaste#318]
### Describe the problem

建议可以在菜单栏隐藏图标（Mac OS）

### Describe the solution you'd like

建议可以在菜单栏隐藏图标

**Comment by ayangweb** [comment]
Duplicate of #289 

收到反馈，此问题将被关闭，等待后续支持！

**Comment by ayangweb** [comment]
#475 已支持！
