### ISSUE TITLE
[feat] 跟随鼠标呼出在跨屏幕中不能正确跟随

### ISSUE THREAD

**Issue by tntll** [ayangweb/EcoPaste#319]
### Describe the problem

![image](https://github.com/user-attachments/assets/9d330df9-cc84-4a5d-9f81-8cc3496c1323)
跨屏幕呼出会在主屏幕侧边展示 不能正确在鼠标所在屏幕展示

### Describe the solution you'd like

能正确跟随鼠标跨屏呼出

**Comment by ayangweb** [comment]
Duplicate of #64 

收到反馈，问题重复，此 issue 将关闭，等待后续版本优化🌹

**Comment by ayangweb** [comment]
Duplicate of #64 

收到反馈，问题重复，此 issue 将关闭，等待后续版本优化🌹

**Comment by ayangweb** [comment]
你好，#413 已经优化，欢迎加入我们的[微信群](https://github.com/ayangweb/EcoPaste?tab=readme-ov-file#community)进行测试🌹
