### ISSUE TITLE
[feat] 可以快捷的开启或者关闭监听

### ISSUE THREAD

**Issue by TimelessDreamer** [ayangweb/EcoPaste#321]
### Describe the problem

可以快捷的开启或者关闭监听功能，这样在不需要监听复制内容时，无需退出 app。

### Describe the solution you'd like

可以快捷的开启或者关闭监听功能，这样在不需要监听复制内容时，无需退出 app。

**Comment by ayangweb** [comment]
收到反馈，后续版本会支持🌹
