### ISSUE TITLE
[feat] 增加默认复制为纯文本功能

### ISSUE THREAD

**Issue by gyunlyun** [ayangweb/EcoPaste#339]
### Describe the problem

现在复制默认带有外观格式。
![image](https://github.com/user-attachments/assets/3b4ceb8d-96c2-473b-87b6-e27c78e9b6ac)

### Describe the solution you'd like

期望增加开关控制默认复制纯文本。
![image](https://github.com/user-attachments/assets/be9e4e75-4eb9-42d3-935f-060aef663e0c)

### Additional context

{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}

**Comment by ayangweb** [comment]
收到反馈，后续版本会支持🌹

**Comment by Faith-Mian** [comment]
也可换个思路，复制内容不改也行，比如改成win+v粘贴纯文本，alt+v粘贴原格式。

**Comment by ayangweb** [comment]
#351 已支持，期待下个版本！

**Comment by ayangweb** [comment]
> 也可换个思路，复制内容不改也行，比如改成win+v粘贴纯文本，alt+v粘贴原格式。

这个思路详见 #320
