### ISSUE TITLE
代码复制后显示为乱码

### ISSUE THREAD

**Issue by lijiaxiucai** [ayangweb/EcoPaste#341]
### Describe the bug

从IED中复制了一段代码，直接粘贴到其它地方是可以的，但在软件中显示为乱码。
乱码如下图所示：
![image](https://github.com/user-attachments/assets/de4d1269-0f22-4481-a07e-c5dfa5b22e24)
正常应该是：
![image](https://github.com/user-attachments/assets/4e71bfa5-3cc5-4c14-9272-85b891561f72)
并且不可通过点击，将其粘贴到其它地方。

### Expected behavior

代码也能正常显示，保留原格式，能正常点击后自动粘贴。

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by ayangweb** [comment]
Duplicate of #36 

问题重复，此 issue 将关闭，等待后续修复🌹

**Comment by ayangweb** [comment]
#414 已优化🌹
