### ISSUE TITLE
快捷键设置时无法使用win键

### ISSUE THREAD

**Issue by lijiaxiucai** [ayangweb/EcoPaste#343]
### Describe the problem

默认的快捷键与其它软件的快捷键功能有冲突，想设置【开始菜单win键+C】的形式，但软件一直把win键识别成alt键。导致无法设置成想要的快捷键。

### Describe the solution you'd like

快捷键设置，可以支持键盘任意键的组合。

**Comment by ayangweb** [comment]
带上按键显示工具录个屏幕看看

**Comment by amaoo** [comment]
@lijiaxiucai 
目前可以通过 微软官方工具 [PowerToys](https://github.com/microsoft/PowerToys/releases) 去实现
![image](https://github.com/user-attachments/assets/049e099f-3de4-4924-9e58-fc1bba81a7f9)

**Comment by ayangweb** [comment]
正如 @amaoo 所说，windows 需要借助工具来映射来使用 `win` 按键，我将关闭此问题，如果有其它任何问题，欢迎随时反馈🌹
