### ISSUE TITLE
[bug] windows 粘贴记录不显示图片

### ISSUE THREAD

**Issue by cyzzxc** [ayangweb/EcoPaste#344]
### Describe the bug

![Snipaste_2024-08-08_10-49-30](https://github.com/user-attachments/assets/8bdaa3a3-5abd-403d-ab44-9f9c518fe308)
粘贴记录中图片部分是完全空白的，但是软件的相关目录下又能找到缓存的截图（文本和文件功能工作正常）

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.4",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by ayangweb** [comment]
截图看看剪切板 app 里面显示的情况🌹

**Comment by cyzzxc** [comment]
![Snipaste_2024-08-08_10-49-30](https://github.com/user-attachments/assets/f8de728b-510f-449d-98ad-37ef37d052ef)
![Snipaste_2024-08-08_13-26-59](https://github.com/user-attachments/assets/fc323d77-d1bb-49a1-a105-da8ef2d7c825)

**Comment by ayangweb** [comment]
这个正常，和 #151 重复，等优化🌹
