### ISSUE TITLE
[bug] 搜索框无法输入中文

### ISSUE THREAD

**Issue by Le-u** [ayangweb/EcoPaste#345]
### Describe the bug

打开剪贴板后，在搜索框内使用中文输入，会对界面进行卡死，无法删除
![Snipaste_2024-08-08_15-35-38](https://github.com/user-attachments/assets/10a836c2-ab73-4f0c-a7a3-56d9e382416f)
和取消，只有在右下角右键软件图标时，才会恢复

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by ayangweb** [comment]
收到反馈，我们下来看一下，win 10 是吧？

**Comment by Le-u** [comment]
> 收到反馈，我们下来看一下，win10 是吧？
我刚刚试了一下win11也不行，都是相同的问题

**Comment by ayangweb** [comment]
好嘞，我看看！

**Comment by ayangweb** [comment]
要不你加下[微信群](https://github.com/ayangweb/EcoPaste?tab=readme-ov-file#community)，有最新的安装包，我没录视频，我不确定你说的是不是，输入的过慢会导致失去焦点，没办法输入，如果是这个问题的话，已经解决了，下个版本就可以正常使用！

**Comment by ayangweb** [comment]
你好，由于这个 issue 长时间没有得到回复，我将先关闭它。你可以前往 [此链接](https://github.com/ayangweb/EcoPaste/actions/workflows/beta_build.yml) 下载最新的测试版进行体验。如果问题仍然存在，请告知我，我会重新打开 issue！
