### ISSUE TITLE
[feat] 剪贴板历史记录快捷删除

### ISSUE THREAD

**Issue by wumingshi32767** [ayangweb/EcoPaste#358]
### Describe the problem

剪贴板历史记录目前的删除只能是选中，然后用鼠标点击删除，粘贴操作几乎都是键盘完成，再切到鼠标操作会显得很麻烦

### Describe the solution you'd like

建议增加选中状态下，按Delete键可以删除当前历史记录的功能

**Comment by ayangweb** [comment]
收到反馈，后续会增加此功能🌹
