### ISSUE TITLE
[bug] M3 pro打开显示包损坏

### ISSUE THREAD

**Issue by cjsvaxlp** [ayangweb/EcoPaste#368]
### Describe the bug

<img width="260" alt="image" src="https://github.com/user-attachments/assets/9bc02e80-d266-479a-9bde-26298f2aebef">

### Application and system information

```text
<img width="260" alt="image" src="https://github.com/user-attachments/assets/9bc02e80-d266-479a-9bde-26298f2aebef">
```

**Comment by ayangweb** [comment]
https://github.com/ayangweb/EcoPaste?tab=readme-ov-file#qa
