### ISSUE TITLE
[bug] Mac版本 多显示器的情况下，呼出窗口选择的跟随鼠标和屏幕中央不能正确的，显示在正在使用的显示器中

### ISSUE THREAD

**Issue by SongOrange666** [ayangweb/EcoPaste#369]
### Describe the bug

Mac版本 多显示器的情况下，呼出窗口选择的跟随鼠标和屏幕中央不能正确的，显示在正在使用的显示器中

### Application and system information

```text
EcoPaste_0.0.5_x64.dmg   Mac intel版本  14.5 (23F79)
```

**Comment by ayangweb** [comment]
Duplicate of #64 

问题重复，此 issue 将被关闭，期待修复
