### ISSUE TITLE
[bug] Ubuntu 24.04 界面不显示

### ISSUE THREAD

**Issue by suhanyujie** [ayangweb/EcoPaste#373]
### Describe the bug

环境：Ubuntu 24.04，wayland，amd 架构
使用 github action 中基于 ubuntu 20.04 环境打的包，运行后，界面是透明的，什么也看不到：
![image](https://github.com/user-attachments/assets/e6640efb-f7c4-46d8-a5d3-5d8f471a8c16)

如果是开发模式 `pnpm tauri dev`，则偏好设置界面可以显示，但用快捷键还是无法显示出剪切板列表：
![image](https://github.com/user-attachments/assets/b9f8f199-6260-4bbd-b82e-300242f88feb)

如果用 tauri 脚手架刚创建的项目测试，打包后运行，是可以正常显示的：
![image](https://github.com/user-attachments/assets/62996e6b-387f-4619-8a25-68ba24a17624)

此外，其他家的剪切板工具 copyQ 在 wayland 下也有一些已知问题，可以参考：
https://copyq.readthedocs.io/en/latest/known-issues.html#known-issue-wayland

### Reproduction

在 `环境：Ubuntu 24.04，wayland，amd 架构 `  中运行 eco-paste 程序

### Expected behavior

1.期望界面正常显示
2.能调出剪切板列表

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Linux",
  "platformArch": "x86_64",
  "platformVersion": "24.4.0"
}
```
```


### Additional context

_No response_

**Comment by suhanyujie** [comment]
经过和一哥测试，直接运行 `src-tauri/target/release/eco-paste` 文件，可以展示界面。因此推断 appimage 包有问题。

**Comment by zpp0196** [comment]
#438
