### ISSUE TITLE
[bug] 经常无故退出

### ISSUE THREAD

**Issue by cethink** [ayangweb/EcoPaste#374]
### Describe the bug

运行一段时间后再看托盘就没有了，快捷菜单也无效了，要重新启动才行，过一会儿就又退出了

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by cethink** [comment]
[Report.zip](https://github.com/user-attachments/files/16597515/Report.zip)
Crash文件

**Comment by zpp0196** [comment]
很容易复现的话可以试一下这个测试版本 https://github.com/ayangweb/EcoPaste/actions/runs/10361714469

**Comment by ayangweb** [comment]
@cethink 怎么样，试了没，也可以进[微信群](https://github.com/ayangweb/EcoPaste?tab=readme-ov-file#community)试一下最新的包

**Comment by cethink** [comment]
试了，好了

**Comment by ayangweb** [comment]
Duplicate of #303 

OK，那我先关了这个 issue 了
