### ISSUE TITLE
[bug] Upon startup, two applications will be opened and two icons will appear in the status bar.

### ISSUE THREAD

**Issue by Kris20030907** [ayangweb/EcoPaste#375]
### Describe the bug

Upon startup, two applications will be opened and two icons will appear in the status bar.

If closing one leaves a backend, it is available，The following figure shows the display of the program dock, which has two programs launched：
<img width="478" alt="image" src="https://github.com/user-attachments/assets/27e6e03a-ae6c-4c07-8c49-08b03b12e02d">

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.5",
  "tauriVersion": "1.7.1",
  "platform": "Darwin",
  "platformArch": "x86_64",
  "platformVersion": "14.4.0"
}
```

**Comment by ayangweb** [comment]
<img width="745" alt="image" src="https://github.com/user-attachments/assets/52c4d951-8607-438a-9f04-3b8ba59d51c4">

Try turning it off and try again!

**Comment by Kris20030907** [comment]
What I mean is that the software will start two, it's not just a display issue for the program dock
![image](https://github.com/user-attachments/assets/d1ffcc27-86d9-488e-ab87-06796d071153)

**Comment by Kris20030907** [comment]
> What I mean is that the software will start two, it's not just a display issue for the program dock ![image](https://private-user-images.githubusercontent.com/99409434/358137546-d1ffcc27-86d9-488e-ab87-06796d071153.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MDI5NjEsIm5iZiI6MTcyMzcwMjY2MSwicGF0aCI6Ii85OTQwOTQzNC8zNTgxMzc1NDYtZDFmZmNjMjctODZkOS00ODhlLWFiODctMDY3OTZkMDcxMTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA2MTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4Mzg3N2JkZTA0MGQzZTFhYjRhYTkwMWE5Y2ZlNmNmNjg1NTMxYmEzNTg1MGMyZjFiNDQ1NzgxZjEyODI4NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wz7MI6mnEgXJ2kItV3jgr7DaGUKjHbn8-_d5aWWnphU)

And currently exit the current window (cmd+q), so that a software can be kept running

**Comment by ayangweb** [comment]
Record a video of the procedure of opening several apps at the same time!

**Comment by ayangweb** [comment]
Hi, since this issue has gone unanswered for a long time, I'm going to go ahead and close it. You can head over to [this link](https://github.com/ayangweb/EcoPaste/actions/workflows/beta_build.yml) to download the latest beta for your experience. If the problem persists, please let me know and I will re-open the issue!
