### ISSUE TITLE
希望增加一个当剪贴板改变时，显示一个弹窗

### ISSUE THREAD

**Issue by rentianyu** [ayangweb/EcoPaste#376]
### Describe the problem

- 实现剪贴板变动通知

### Describe the solution you'd like

- 希望增加一个当剪贴板改变时，显示一个弹窗
- 如下图

![image](https://github.com/user-attachments/assets/3cab1116-faab-4014-8601-cac98b2e9efe)

**Comment by ayangweb** [comment]
和 #286 应该是类似的吧？

**Comment by rentianyu** [comment]
> 和 #286 应该是类似的吧？

是的，麻烦了

**Comment by ayangweb** [comment]
Duplicate of #286 

好的，那重复的 issue 我先关了，后续等支持🌹
