### ISSUE TITLE
希望出个 Windows 便携版

### ISSUE THREAD

**Issue by YandLiu** [ayangweb/EcoPaste#377]
### Describe the problem

不用安装，方便备份迁移

### Describe the solution you'd like

不用安装，另外就是把软件、用户数据、设置等都放在一块，就像 Ditto

**Comment by ayangweb** [comment]
Duplicate of #270 

问题重复，此issue 将被关闭！下个版本开始会提供绿色版🌹

**Comment by ayangweb** [comment]
https://github.com/ayangweb/EcoPaste/releases/download/v0.0.6/EcoPaste_0.0.6_Windows_x64_Portable.zip

最新版已加入！

**Comment by YandLiu** [comment]
目前程序数据还是保存在%APPDATA%里，并没有做到跟程序放一起，建议都放一起

**Comment by ayangweb** [comment]
Duplicate of #163 后续支持
