### ISSUE TITLE
[bug] 页面排版在2k分辨率小出现横线滚动条BUG

### ISSUE THREAD

**Issue by GongLe** [ayangweb/EcoPaste#386]
### Describe the bug

1、【BUG】页面排版在2k分辨率小出现横线滚动条BUG
2、【建议】面板记录单项高度默认自适应，或可设置固定高度和自适应高度（随内容大小）扩充，这样UI可以容纳更多记录。
3、【建议】呼出面板高度、宽度可以自定义，即鼠标拖动控制大小，这样更加人性化
最后祝大佬天天开心，事事顺心
![Clip_2024-08-18_14-49-26](https://github.com/user-attachments/assets/570a7494-1f80-4739-adde-fd76babc0b3f)

### Reproduction

![Clip_2024-08-18_14-50-16](https://github.com/user-attachments/assets/15a0fdd8-a783-486e-8a03-ae1cde6b2220)

### Application and system information

```text
Windows11专业工作站版64位（10.0，版本22631)
名称：:Intel(R) UHD Graphics 630
制造商：：IntelCorporation
芯片类型：:Intel(R) UHD Graphics Family
```

**Comment by ayangweb** [comment]
收到反馈，#306 已优化，期待更新🌹
