### ISSUE TITLE
[feat] 增加个性化参数，选项卡增加记住上次选中

### ISSUE THREAD

**Issue by GongLe** [ayangweb/EcoPaste#389]
### Describe the problem

1、增加个性化参数，选项卡增加记住上次选中，这样方便下次呼出依然能选定制定类型；
2、UI列表上方先的太拥挤，下方留白太多，建议先行操作栏，鼠标hover再显示，这样显得版面简洁。个性化参数开关更好

### Describe the solution you'd like

![Clip_2024-08-19_09-09-27](https://github.com/user-attachments/assets/29c59ff6-0adb-46f6-8368-ca367b80b165)

**Comment by ayangweb** [comment]
1. 记住位置会在后续和 #272 一起做。
2. 后续支持🌹
