### ISSUE TITLE
[bug] 软件打开一直闪

### ISSUE THREAD

**Issue by 2698991620** [ayangweb/EcoPaste#408]
### Describe the bug

软件一直闪无法使用

### Application and system information

```text
软件一直闪无法使用
```

**Comment by ayangweb** [comment]
Duplicate of #269 详见这个 issue

**Comment by ayangweb** [comment]
加入[微信群](https://github.com/ayangweb/EcoPaste?tab=readme-ov-file#community) 第一时间上手最新的测试版本🌹

**Comment by ayangweb** [comment]
问题重复，我先关了，有其它问题关于随时反馈
