### ISSUE TITLE
[feat] 多显示器情况下，希望选择框能跟随屏幕

### ISSUE THREAD

**Issue by willron** [ayangweb/EcoPaste#410]
### Describe the problem

MAC系统，多屏幕的情况下，在副屏工作使用自定义热键呼出剪贴板文本选择框，始终是在主屏出现，不是很方便

### Describe the solution you'd like

希望能出现在焦点显示屏上

### Additional context

Mac mini Apple M1
macOS Sonoma 14.6.1
Display screen *2

**Comment by ayangweb** [comment]
Duplicate of #64 

问题重复，此 issue 将被关闭，等待后续优化🌹

**Comment by ayangweb** [comment]
你好，#413 已经优化，欢迎加入我们的[微信群](https://github.com/ayangweb/EcoPaste?tab=readme-ov-file#community)进行测试🌹
