### ISSUE TITLE
[bug] 有时粘贴会无法粘贴，反而会把触发快捷键给输出出来

### ISSUE THREAD

**Issue by MacReeee** [ayangweb/EcoPaste#411]
### Describe the bug

我的触发快捷键为cmd+shift+v，可以正常呼出窗口，但是鼠标点选需要粘贴的内容后，有时会输出一个字符‘v’

触发视频（存在爆音，请注意音量）：
https://github.com/user-attachments/assets/8b24a385-a952-4eb7-b351-85944115aef7

### Application and system information

```text
macOS 15.1 bete
```

**Comment by ayangweb** [comment]
#360 已优化此问题，期待下个版本发布，也可以加入 README 里的微信群，提前体验测试版本！
