### ISSUE TITLE
[feat] 建议添加一个排除功能

### ISSUE THREAD

**Issue by LilJohn419** [ayangweb/EcoPaste#412]
### Describe the problem

有些绘图软件复制的内容没有意义，徒增资源占用

### Describe the solution you'd like

建议可以像mac上Paste一样，给用户做选择
![image](https://github.com/user-attachments/assets/cca16a7b-ac5c-47ce-a23b-2012a1dfed2d)

**Comment by ayangweb** [comment]
Duplicate of #285 

问题重复，此 issue 将被关闭，等待后续优化！
