### ISSUE TITLE
功能添加

### ISSUE THREAD

**Issue by NingJingi** [ayangweb/EcoPaste#425]
从Word或者网页复制的时候，会把格式也复制出来，是否可以添加个选项，按格式或者纯文本粘贴

**Comment by ayangweb** [comment]
收到反馈，已经支持，周末新版本发布🌹

<img width="730" alt="image" src="https://github.com/user-attachments/assets/61557d6c-5f6f-4be8-b422-2c6a4a6217d0">

<img width="390" alt="image" src="https://github.com/user-attachments/assets/11b87382-143d-49dd-a3b5-8df48699cc72">
