### ISSUE TITLE
[bug] 安装后出现“偏好设置”界面闪退并启动，循环如此。

### ISSUE THREAD

**Issue by MeizhouWan** [ayangweb/EcoPaste#427]
### Describe the bug

我在任务管理器翻到最底才能把它停止。
下次试图复现此bug，我打算录制它的情况，奈何失败，于是再打开任务管理器切回，发现它已经停止此bug。:(

### Application and system information

```text
今天最新版 win10 22h2 19045.4780
```

**Comment by ayangweb** [comment]
Duplicate of #269 

已修复此问题，周末会发布新版，你也可以提前下载最新的测试版本体验：https://github.com/ayangweb/EcoPaste/actions/runs/10522705739
