### ISSUE TITLE
[bug] 快捷键设置无效

### ISSUE THREAD

**Issue by cethink** [ayangweb/EcoPaste#445]
### Describe the bug

![image](https://github.com/user-attachments/assets/023d6379-c7a6-4a8a-8070-87567d5a1dfc)
快捷设置重启系统就失效了

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.6",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by cethink** [comment]
重启就恢复默认了

**Comment by ayangweb** [comment]
收到反馈，我们来测试下！

**Comment by ayangweb** [comment]
你好，我在测试过程中，并未能复现此问题，要不你备份下数据，然后卸载重装一下试试？

https://github.com/user-attachments/assets/fb6ec735-4c79-40f6-8761-5562b30d3bca

**Comment by cethink** [comment]
卸载清理后重装就好了

**Comment by cethink** [comment]
卸载清理后重装就好了
