### ISSUE TITLE
[bug] vscode、vs2022 粘贴问题

### ISSUE THREAD

**Issue by WyInnovate** [ayangweb/EcoPaste#453]
### Describe the bug

# 问题
1. 在vs2022中，需要软件使用管理员权限启动，才能够粘贴纯文本、HTML，否则只能点击复制按钮后粘贴
2. 在vs2022中，无法双击粘贴、点击复制按钮后粘贴 富文本
3. 在vscode中，无法双击粘贴、点击复制按钮后粘贴 富文本

### Reproduction

无

### Expected behavior

无

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.6",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
收到反馈，等我抽空排查一下🌹

**Comment by ayangweb** [comment]
关于管理员权限的问题，是只有这 vs 2022 这一个软件出现这个问题吗？其它软件都正常不用开启吗？
