### ISSUE TITLE
[feat] 竟然有了便携版，为什么不把“数据保存目录”也自定义化呢？

### ISSUE THREAD

**Issue by xiawiner** [ayangweb/EcoPaste#456]
### Describe the problem

这个软件很棒，我喜欢使用便携版，很遗憾数据保存目录无法自定义存储位置，只能保存在C盘，由于使用了一些系统还原的软件，这些数据就丢失了，希望可以自定义数据保存目录，感谢作者！

### Describe the solution you'd like

这个软件很棒，我喜欢使用便携版，很遗憾数据保存目录无法自定义存储位置，只能保存在C盘，由于使用了一些系统还原的软件，这些数据就丢失了，希望可以自定义数据保存目录，感谢作者！

**Comment by ayangweb** [comment]
Duplicate of #163 

问题重复，此 issue 将被关闭，等后续支持🌹

**Comment by ayangweb** [comment]
虽然数据不在同一目录，但是想卸载的话执行 uninstall.exe 并选择删除应用程序数据也是可以的哈！

<img width="533" alt="image" src="https://github.com/user-attachments/assets/dbf5d2c2-2417-47c9-9c59-3e862236ed35">
