### ISSUE TITLE
[bug] 默认主题模式不能适应系统

### ISSUE THREAD

**Issue by cethink** [ayangweb/EcoPaste#460]
### Describe the bug

我是暗色主题，安装完默认是亮色，修改一下之后就好了。另外提示重启app的弹窗如果取消重启则会有两个弹窗
![image](https://github.com/user-attachments/assets/3f020752-bde3-414f-a62e-36d24e144d5c)

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.6",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.22631"
}
```

**Comment by ayangweb** [comment]
1. 本次更新确实弃用了旧版 UI 的配置项，需要您重新配置，给您带来的不便，敬请谅解。
2. 弹框的问题我会抽空排查一下。

**Comment by cethink** [comment]
我的意思是装完默认是跟随系统，我的系统是暗色，但窗口是亮色，没有跟随，修改之后就可以了

**Comment by ayangweb** [comment]
嗯，是旧的配置项的问题，重新修改一次就可以！

**Comment by WyInnovate** [comment]
@ayangweb 主题模式，如果切换后点了取消应该是恢复之前的主题模式，但是还是新选择的主题模式，然后弹窗两次的问题普遍存在，当你从跟随系统切换为亮色的时候，就会有两个重叠的弹窗

**Comment by ayangweb** [comment]
> @ayangweb 主题模式，如果切换后点了取消应该是恢复之前的主题模式，但是还是新选择的主题模式，然后弹窗两次的问题普遍存在，当你从跟随系统切换为亮色的时候，就会有两个重叠的弹窗

收到反馈，恢复的问题确实没考虑到，然后弹框问题我下来再排查下！

**Comment by cethink** [comment]
> 嗯，是旧的配置项的问题，重新修改一次就可以！

没有跟随系统设置这难道不是个BUG？

**Comment by ayangweb** [comment]
> > 嗯，是旧的配置项的问题，重新修改一次就可以！
> 
> 没有跟随系统设置这难道不是个BUG？

嗯，录个视频看看吧，我不清楚是只有首次更新没有跟随，还是不管如何设置都不更新，没有说太明白！

**Comment by cethink** [comment]
> > > 嗯，是旧的配置项的问题，重新修改一次就可以！
> > 
> > 
> > 没有跟随系统设置这难道不是个BUG？
> 
> 嗯，录个视频看看吧，我不清楚是只有首次更新没有跟随，还是不管如何设置都不跟随，没太理解！

就是安装完默认是跟随系统，但没有跟随，比如我的是暗色，但窗口是亮色

**Comment by ayangweb** [comment]
> > > > 嗯，是旧的配置项的问题，重新修改一次就可以！
> > > 
> > > 
> > > 没有跟随系统设置这难道不是个BUG？
> > 
> > 
> > 嗯，录个视频看看吧，我不清楚是只有首次更新没有跟随，还是不管如何设置都不跟随，没太理解！
> 
> 就是安装完默认是跟随系统，但没有跟随，比如我的是暗色，但窗口是亮色

哦哦，这下我懂了，那确实是个 bug，我来排查一下🌹

**Comment by ayangweb** [comment]
复现出来了，这是全平台的问题，初始化 app 没有判断 auto 时的主题模式！

**Comment by ayangweb** [comment]
弹框问题是我在 [App.tsx](https://github.com/ayangweb/EcoPaste/blob/3a31ee9fb64c5b73bdc44836c98f8dce6f9e1979/src/App.tsx#L35) 里写了弹框，每一个窗口都会执行一次，这就导致多弹框的问题！

**Comment by ayangweb** [comment]
Windows 系统确实存在一些不足之处，主要表现在版本繁多且杂乱，API 也不一致。此外，它缺乏一种兼容性良好、能够无感知切换主题的完整解决方案。

**Comment by ayangweb** [comment]
@cethink https://github.com/ayangweb/EcoPaste/actions/runs/10571805489 试一下首次打开跟随系统的！

**Comment by cethink** [comment]
黑了。另外提示框切换到亮色取消只有一次，再切换到跟随取消还是有两次

**Comment by ayangweb** [comment]
> 黑了。另外提示框切换到亮色取消只有一次，再切换到跟随取消还是有两次

OK，弹框会在新的 pr 修复！

**Comment by ayangweb** [comment]
https://github.com/ayangweb/EcoPaste/actions/runs/10576046558 尝试下最新测试版！

**Comment by cethink** [comment]
可以了，就是安装完会闪三次弹窗，其他都好了

**Comment by ayangweb** [comment]
> 可以了，就是安装完会闪三次弹窗，其他都好了

这个 bug 我也有复现，我下来再优化下！
