### ISSUE TITLE
[bug] ram usage increased fast!!!

### ISSUE THREAD

**Issue by Kenoncloud** [ayangweb/EcoPaste#465]
### Describe the bug

when I call it, the ram usage  increased fast! most 3Ghz

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.6",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by ayangweb** [comment]
Can you explain exactly why it was created? Was a large amount of text copied? Like tens of thousands of texts?

**Comment by Kenoncloud** [comment]
I don't know what caused it either. I was just using it normally, with only a few paragraphs of text and screenshots. When I used the shortcut keys to call up the program, suddenly the program froze. I opened the task manager and saw that the RAM memory was occupying a lot, and there were several webview2 processes. I don't know if it was caused by Edge. This problem occasionally occurred today, but it quickly recovered. I don't know exactly what caused it

**Comment by Kenoncloud** [comment]
![bug](https://github.com/user-attachments/assets/5f14dcf9-cdff-4d0f-8e8a-5879b707d754)
it crashed again when i restarted the program,and the ram almost 7G . Please look look.

**Comment by Kenoncloud** [comment]
> Can you explain exactly why it was created? Was a large amount of text copied? Like tens of thousands of texts?

hi, please take attention of my issue

**Comment by Kenoncloud** [comment]
> > Can you explain exactly why it was created? Was a large amount of text copied? Like tens of thousands of texts?
> 
> hi, please take attention of my issue

when I exit and restart the program, the shortcut keys seem to be offline. but aften several minutes, it opened but frozed(can not do anything)

**Comment by ayangweb** [comment]
Download the latest beta version and try it: https://github.com/ayangweb/EcoPaste/actions/runs/10623582585

Keep the feedback coming!

**Comment by Kenoncloud** [comment]
No response
![Uploading bug4.png…]()

**Comment by Kenoncloud** [comment]
![bug4](https://github.com/user-attachments/assets/a195096f-044d-441e-8b8a-aa2f8725800b)

**Comment by ayangweb** [comment]
Okay, this will have to come down to a slow troubleshooting!

**Comment by Kenoncloud** [comment]
Maybe problem is the database is  too large, when i delete the EcoPaste.db, all will be right.

**Comment by ayangweb** [comment]
OK, I think it's also caused by too much data, I'll optimize the loading of data down the road, currently it's a full batch request, a bit too much of a performance loss!
