### ISSUE TITLE
[feat] 回车粘贴内容

### ISSUE THREAD

**Issue by 1250456532** [ayangweb/EcoPaste#61]
### Describe the problem

alt+c 唤醒面板后，上下键可以选择内容，但回车键无法选中粘贴

### Describe the solution you'd like

新增回车键选中粘贴功能

**Comment by ayangweb** [comment]
感谢反馈！#29 我们还在进一步实现回填的功能，等实现功能后我们会通过自定义选项的方式来支持此功能！

**Comment by ayangweb** [comment]
Duplicate of #29

**Comment by ayangweb** [comment]
问题重复，我先关了，等后续版本支持哦！

**Comment by ayangweb** [comment]
#169 功能已实现，期待下个版本！
