### ISSUE TITLE
[bug] m1 macos 切换主题多点几次开始鬼畜

### ISSUE THREAD

**Issue by Pursuemc** [ayangweb/EcoPaste#63]
### Describe the bug

m1 macos 切换主题多点几次开始鬼畜

### Reproduction

https://github.com/ayangweb/EcoPaste/assets/59902873/9e33ec38-0eaf-4848-8ab2-52bc063adbf0

### Expected behavior

正常切换主题

### Application and system information

```text
m1 macos Sonoma 14.5
```

**Comment by ayangweb** [comment]
感谢您的反馈！经过测试，的确是有这个问题。关于主题切换的功能，我们会认真考虑其必要性和可行性。

**Comment by ayangweb** [comment]
#79 已修复，期待下个版本！
