### ISSUE TITLE
[bug] 双屏幕时，窗口位置【跟随鼠标】窗口位置偏差

### ISSUE THREAD

**Issue by kohaiy** [ayangweb/EcoPaste#64]
### Describe the bug

两个屏幕的时候，【窗口位置】选择【跟随鼠标】，在副屏幕上召唤窗口，依旧在主屏幕右下角出现。

### Reproduction

【窗口位置】选择【跟随鼠标】，在副屏幕上召唤窗口

### Expected behavior

能够正确获取屏幕信息，窗口显示在副屏幕上。

### Application and system information

```text
{
  "appName": "EcoPaste",
  "appVersion": "0.0.2",
  "tauriVersion": "1.7.1",
  "platform": "Windows_NT",
  "platformArch": "x86_64",
  "platformVersion": "10.0.19045"
}
```

**Comment by ayangweb** [comment]
感谢您的反馈！我们会尽快解决这个问题。
