### ISSUE TITLE
[feat] win11使用，感觉软件有些不合理的地方

### ISSUE THREAD

**Issue by nsnans** [ayangweb/EcoPaste#65]
## 这个不应该做成透明的，安装完，我都以为应用没开。

![image](https://github.com/ayangweb/EcoPaste/assets/68949154/f145e2f0-8560-4990-96a9-9c77e7c4263b)

## 快捷键应当根据平台展示不同的，没看懂这快捷键是什么意思

![image](https://github.com/ayangweb/EcoPaste/assets/68949154/bc854f9a-db3c-4b4f-9bb7-86329f46b4bc)
![image](https://github.com/ayangweb/EcoPaste/assets/68949154/632a563a-1476-4475-b739-e581556468af)

### Describe the solution you'd like

- logo做成正常的，一看托盘就知道打开了这个软件
- 快捷键根据平台显示正常，并且希望可以自定义
- 添加剪贴数据库管理功能

### Additional context

win11，刚安装，看不懂这快捷键，不知道怎么使用，所以剪贴功能什么的没试。

**Comment by ayangweb** [comment]
> ### Describe the problem
> ## 这个不应该做成透明的，安装完，我都以为应用没开。
好的，这个我会重新制作托盘 logo 来适配 windows 平台
> ![image](https://private-user-images.githubusercontent.com/68949154/346413374-f145e2f0-8560-4990-96a9-9c77e7c4263b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDgyNzcsIm5iZiI6MTcyMDQwNzk3NywicGF0aCI6Ii82ODk0OTE1NC8zNDY0MTMzNzQtZjE0NWUyZjAtODU2MC00OTkwLTk2YTktOWM3N2U3YzQyNjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAzMDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwN2E2MWYzMDM4OTY5OTJhYjk4NTk5NjQwZGVkMDI0NzVlODI1N2QxMzY5MDQ0NjE0ZjZlYWNmYWVkOWNhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9056Xxeo_hB52pj3wLz-9LsAlQUGZ2dnJK3SrLJE31U)
> 
> ## 快捷键应当根据平台展示不同的，没看懂这快捷键是什么意思
好的，你有任何的 windows app 快捷键设置的示例吗？我可以作为参考来进行适配！
> ![image](https://private-user-images.githubusercontent.com/68949154/346413943-bc854f9a-db3c-4b4f-9bb7-86329f46b4bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDgyNzcsIm5iZiI6MTcyMDQwNzk3NywicGF0aCI6Ii82ODk0OTE1NC8zNDY0MTM5NDMtYmM4NTRmOWEtZGIzYy00YjRmLTliYjctODYzMjlmNDZiNGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAzMDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4M2NhNTg1MDRlOTQzNDVkMGQ2NWU0YmE4NDE0YzBjNjY1NTE2YTA1OWE3YmUxYjJlNzdlOWIwMDE4MzRhZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PBOYMs_5Ce8-eg6aSrareUV1bkAUh-neQo2WFTpQu40) ![image](https://private-user-images.githubusercontent.com/68949154/346414126-632a563a-1476-4475-b739-e581556468af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MDgyNzcsIm5iZiI6MTcyMDQwNzk3NywicGF0aCI6Ii82ODk0OTE1NC8zNDY0MTQxMjYtNjMyYTU2M2EtMTQ3Ni00NDc1LWI3MzktZTU4MTU1NjQ2OGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAzMDYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MGMzMDAwNjViMTgwZDk2YTQ2ZDIyMmE1ZTk0NjcxYTc1OWU0MTAyOTNiMWQzMjA0ZmUxY2NkNzA2ZDUxNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B16jaWWO4lVaLLGISR1HxPZAwRbGSLKhgigCGMXCRlk)
> 
> ## 我觉得应该需要和ditto一样，有设置数据库路径，和导出和导入功能
好，关于这个问题我们会考虑逐步去支持！
> ### Describe the solution you'd like
> * logo做成正常的，一看托盘就知道打开了这个软件
> * 快捷键根据平台显示正常，并且希望可以自定义
> * 添加剪贴数据库管理功能
> 
> ### Alternatives considered
> _No response_
> 
> ### Additional context
> win11，刚安装，看不懂这快捷键，不知道怎么使用，所以剪贴功能什么的没试。
windows 系统是 alt+c 哈，可以试试！

感谢反馈！

**Comment by ayangweb** [comment]
感谢反馈！
1. 我们会重新制作托盘图标，以适配 Windows 平台。
2. 快捷键目前是支持自定义的，关于 windows 上的快捷键设置的样式，你有任何好看的示例可以参考的吗？
3. 关于数据存储、导入和导出功能我们会根据用户的需求了逐步去添加！

你想打开剪切板的话，windows 上默认是 alt+c 哈！

**Comment by ayangweb** [comment]
我们已经讨论并决定为 Windows 系统单独适配快捷键。

关于数据存储路径，我们意识到其中可能涉及到一些比较复杂的问题。

数据的导入和导出功能将会尽快支持！

**Comment by ayangweb** [comment]
1. #29 回填功能我们正在逐步完善。
2. 确实有必要显示全部内容！我们将对此展开讨论，并考虑做出相应的改进！

**Comment by ayangweb** [comment]
> > 感谢反馈！
> > 
> > 1. 我们会重新制作托盘图标，以适配 Windows 平台。
> > 2. 快捷键目前是支持自定义的，关于 windows 上的快捷键设置的样式，你有任何好看的示例可以参考的吗？
> > 3. 关于数据存储、导入和导出功能我们会根据用户的需求了逐步去添加！
> > 
> > 你想打开剪切板的话，windows 上默认是 alt+c 哈！
> 
> ## 选中这条，直接粘贴就好，再把这条提升到顶部，用户在这里再去复制粘贴感觉太麻烦了
> ![image](https://private-user-images.githubusercontent.com/68949154/346419477-b411a2e3-0f8f-4a48-9387-a2a40c30883f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTAxODMsIm5iZiI6MTcyMDQwOTg4MywicGF0aCI6Ii82ODk0OTE1NC8zNDY0MTk0NzctYjQxMWEyZTMtMGY4Zi00YTQ4LTkzODctYTJhNDBjMzA4ODNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAzMzgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4OGFkODc4NzFlYzM5MGE0MDg5YTJhNzYyYmRjYjAwNDgxNDU1Yjc3MTJlZjQwZWFiY2RiODIyNzNiOGI0NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CISGCO14t-XpsmpJRdLc3Oa5cy_X87A0BxwUf0unOzA)
> 
> ## 鼠标放在文字上，没有title提示，文字超出了，不能滚动，用户没办法查看全部文字，所以不如和ditto一样，加上title把全部文字显示出来
> ![image](https://private-user-images.githubusercontent.com/68949154/346420339-b259c044-81c3-45df-9d20-f87c7f5239d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MTAxODMsIm5iZiI6MTcyMDQwOTg4MywicGF0aCI6Ii82ODk0OTE1NC8zNDY0MjAzMzktYjI1OWMwNDQtODFjMy00NWRmLTlkMjAtZjg3YzdmNTIzOWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDAzMzgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNGY1ZGM0NjY2MWI4ZWZlOGE4NWNiNjg0NTQxY2Q4MDNlNDY1NWVlMzQyNWM4Y2M5M2M0ZDljZmQ4ZjIzMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.70xOaTVMc4Z1ao1Ynkz4BLH0LwXiEJNnPIwvM6iP_h0)

1. #29 回填功能我们正在逐步完善。
2. 确实有必要显示全部内容！我们将对此展开讨论，并考虑做出相应的改进！

**Comment by ayangweb** [comment]
> 2\. 确实有必要显示全部内容！我们将对此展开讨论，并考虑做出相应的改进！

这部分确实欠考虑，后续会对此进行优化！

**Comment by ayangweb** [comment]
多个功能已经分到单独的 issue 中，这个 issue 我就先关了！有问题欢迎继续反馈！

**Comment by ayangweb** [comment]
#169 功能已实现，期待下个版本！
