### ISSUE TITLE
[feat] 打开之后，在顶部导航栏点击的时候，鼠标左键是打开应用，右键是显示菜单，和常用app操作不一致。

### ISSUE THREAD

**Issue by Pursuemc** [ayangweb/EcoPaste#66]
### Describe the problem

我下的很多应用都是左键菜单，点偏好设置进入app。很多时候仅仅是点出菜单改个设置或者开个开关，并不想打开app，尤其是这种工具类的app。（如icopy,magnet等）

### Describe the solution you'd like

希望改成左键菜单

**Comment by ayangweb** [comment]
感谢反馈，这一点确实与 MacOS 上的应用的操作方式不一致。我们将对此进行讨论，并考虑做出相应的改进！

**Comment by ayangweb** [comment]
#73 下个版本更新将优化此功能！
