### ISSUE TITLE
[feat] windows 单独做快捷键设置样式适配

### ISSUE THREAD

**Issue by ayangweb** [ayangweb/EcoPaste#69]
### Describe the problem

#65

### Describe the solution you'd like

#65 

### Additional context

感谢 @nsnans 大佬的反馈！

**Comment by Azir-11** [comment]
![155532b0aa11c31c5db8c99e3ba904ce](https://github.com/ayangweb/EcoPaste/assets/79054161/f2ae7bef-d9e4-4464-8808-59f1e9e122ba)

**Comment by ayangweb** [comment]
@nsnans #85 已适配，等下个版本！
