### ISSUE TITLE
[style] 搜索功能界面优化

### ISSUE THREAD

**Issue by nsnans** [ayangweb/EcoPaste#98]
### Describe the problem

现在搜索感觉不太美观，也不方便。

![image](https://github.com/ayangweb/EcoPaste/assets/68949154/af344133-e910-4c20-bf3f-012e1b952f1a)

### Describe the solution you'd like

底部一直出现搜索框，只要上面tag可以很方便点击
![image](https://github.com/ayangweb/EcoPaste/assets/68949154/967a8d61-964b-4a54-af3b-52c5a791813a)

**Comment by ayangweb** [comment]
感谢反馈，后续版本会对此问题进行优化

**Comment by wxyShine** [comment]
+1

**Comment by ayangweb** [comment]
#131 期待下个版本更新！
