### ISSUE TITLE
[feat] 设置快捷键可以更友好一点 

### ISSUE THREAD

**Issue by Curllen** [ayangweb/EcoPaste#99]
### Describe the problem

现在快捷键只能A+B键,但是使用时不够方便和友好(高频便捷按的快捷键已经被其他软件占用了)

### Describe the solution you'd like

增加支持A+A快捷键, 例如双击ctr即可唤醒

**Comment by ayangweb** [comment]
感谢反馈！在开发过程中，我已经测试过这个问题。很遗憾，目前 Tauri 提供的快捷键功能尚不支持注册双击按键。

**Comment by ayangweb** [comment]
https://github.com/tauri-apps/tauri/issues/6459

**Comment by ayangweb** [comment]
当然注册快捷键这个功能我想应该可以采用监听键盘按键按下的方式手动实现，这样的话可以实现任意方式的快捷键！[rdev](https://crates.io/crates/rdev)

**Comment by ayangweb** [comment]
这个 issue 我先关闭了。如果有任何其它问题，欢迎再次提问！
